# Generated by Django 6.0.6 on 2026-06-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftSearch',
            fields=[
                ('n_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('owner_name', models.TextField(blank=True, null=True)),
                ('aircraft_manufacturer', models.TextField(blank=True, null=True)),
                ('aircraft_model', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aircraft_search',
            },
        ),
    ]
